name: petani_cerdas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bcrypt: ^1.1.3
  cloud_firestore: ^5.6.0
  d_session: ^0.0.3
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_messaging: ^15.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^9.2.3
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.10
  gap: ^3.0.1
  google_fonts: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  intl: ^0.20.1
  permission_handler: ^11.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/login_top_palm_oil_image.png"
  adaptive_icon_background: "#FFFFFF"

#flutter clean
#flutter pub get
  #flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/empty_transaction.png
    - assets/images/login_bottom_tomatto_image.png
    - assets/images/login_top_palm_oil_image.png
    - assets/icons/
