// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDszINvhGXT42DC0StevyCCYJNV5xe9EeA',
    appId: '1:34550127930:web:ec154873cbc5f154f24403',
    messagingSenderId: '34550127930',
    projectId: 'petanicerdas-8101f',
    authDomain: 'petanicerdas-8101f.firebaseapp.com',
    storageBucket: 'petanicerdas-8101f.firebasestorage.app',
    measurementId: 'G-FE51BEBXGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0XgdNLup3ph_WGZf-rY7U1Mk-gJW3GQ0',
    appId: '1:34550127930:android:8515ecf1ff4c00caf24403',
    messagingSenderId: '34550127930',
    projectId: 'petanicerdas-8101f',
    storageBucket: 'petanicerdas-8101f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ddYAKbXQWp1rIjKY3-DsynD8U7XJ_VM',
    appId: '1:34550127930:ios:6cc15413b50f3871f24403',
    messagingSenderId: '34550127930',
    projectId: 'petanicerdas-8101f',
    storageBucket: 'petanicerdas-8101f.firebasestorage.app',
    iosBundleId: 'com.example.petaniCerdas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ddYAKbXQWp1rIjKY3-DsynD8U7XJ_VM',
    appId: '1:34550127930:ios:6cc15413b50f3871f24403',
    messagingSenderId: '34550127930',
    projectId: 'petanicerdas-8101f',
    storageBucket: 'petanicerdas-8101f.firebasestorage.app',
    iosBundleId: 'com.example.petaniCerdas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDszINvhGXT42DC0StevyCCYJNV5xe9EeA',
    appId: '1:34550127930:web:ab6f6cdb4a61a689f24403',
    messagingSenderId: '34550127930',
    projectId: 'petanicerdas-8101f',
    authDomain: 'petanicerdas-8101f.firebaseapp.com',
    storageBucket: 'petanicerdas-8101f.firebasestorage.app',
    measurementId: 'G-Y1ZXJSSZN4',
  );
}
